[project]
name = "ansible-repo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible-lint>=6.8.7",
    "ansible>=11.0.0",
]
