---
- name: Initialize VM
  import_playbook: playbooks/init-vm/playbook.yml
  tags: init-vm

- name: Initialize LXC
  import_playbook: playbooks/init-lxc/playbook.yml
  tags: init-lxc

- name: Initialize Node
  import_playbook: playbooks/init-node/playbook.yml
  tags: init-node
