# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/common
- name: Install debug tools
  become: true
  ansible.builtin.apt:
    pkg:
      - htop # リソース管理コマンドtopより見やすい。井脇
      - nmap # ポートスキャンでポートの解放状況を確認できる
      - net-tools # (=netstat)tcpのコネクションやポートの解放状況、パケット統計が確認できる。
      - git # ソースコード管理ツール
      - vim # エディタ
      - make # ビルドツール
      - curl # HTTPクライアント
      - wget # HTTPクライアント
    update_cache: true # same as apt-get update
    upgrade: dist # same as apt-get upgrade
