# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/example
- name: Install task cmd
  become: true
  ansible.builtin.copy:
    src: files/task
    dest: /usr/local/bin/task
    owner: "{{ ansible_facts['env']['USER'] }}"
    group: "{{ ansible_facts['env']['USER'] }}"
    mode: '0744'
    backup: true
