# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/example
- name: Install task cmd
  become: "{{ enable_sudo | default(true) }}"
  ansible.builtin.copy:
    src: files/task
    dest: /usr/local/bin/task
    owner: root
    group: root
    mode: '0755'

- name: Set Bash Completion for Task
  become: "{{ enable_sudo | default(true) }}"
  ansible.builtin.copy:
    src: files/task_completion
    dest: /etc/bash_completion.d/task_completion
    owner: root
    group: root
    mode: '0644'

- name: Ensure task_completion is sourced in .bashrc
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "source /etc/bash_completion.d/task_completion"
    state: present
