# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/common
- name: Apt Update
  ansible.builtin.apt:
    update_cache: true

- name: Apt Update and Upgrade
  ansible.builtin.apt:
    upgrade: dist # same as apt-get upgrade
  when: apt_upgrade is true

- name: Install essential packages
  ansible.builtin.apt:
    pkg:
      - htop # リソース管理コマンドtopより見やすい。
      - nmap # ポートスキャンでポートの解放状況を確認できる
      - net-tools # (=netstat)tcpのコネクションやポートの解放状況、パケット統計が確認できる。
      - git # ソースコード管理ツール
      - vim # エディタ
      - make # ビルドツール
      - curl # HTTPクライアント
      - wget # HTTPクライアント
    autoremove: true
