---
- name: Initialize VM
  hosts: proxmox_vm
  roles:
    # - {role: basic_apt_package, enable_sudo: true}
    # - {role: default_configs, enable_sudo: true}
    # - {role: default_cmd, enable_sudo: true}
    # - {role: install_docker, enable_sudo: true}
    # # - {role: setup_exporter, enable_sudo: true}
    # - {role: install_tailscale, enable_sudo: true}
    - {role: asdf_k8s_client, asdf_k8s_client_enable_sudo: true}
