---
- name: Initialize VM
  hosts: proxmox_vm
  roles:
    - {role: basic_apt_package, basic_apt_package_enable_sudo: true}
    - {role: default_configs}
    - {role: default_cmd, default_cmd_enable_sudo: true}
    - {role: install_docker, install_docker_enable_sudo: true}
    - {role: install_tailscale, install_tailscale_enable_sudo: true}
