---
- name: Initialize VM
  hosts: proxmox_vm
  roles:
    - {role: basic_apt_package, enable_sudo: true}
    # - default_configs
    - {role: default_cmd, enable_sudo: true}
    - {role: install_docker, enable_sudo: true}
    - {role: setup_exporter, enable_sudo: true}
    - {role: install_tailscale, enable_sudo: true}
