# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/configs
- name: Copy .bashrc to user's home directory
  ansible.builtin.copy:
    src: files/bashrc
    dest: /{{ ansible_facts.env.HOME }}/.bashrc
    owner: "{{ ansible_facts.env.USER }}"
    group: "{{ ansible_facts.env.USER }}"
    mode: '0644'
    backup: true

- name: Copy .gitconfig to user's home directory
  ansible.builtin.copy:
    src: files/gitconfig
    dest: /{{ ansible_facts.env.HOME }}/.gitconfig
    owner: "{{ ansible_facts.env.USER }}"
    group: "{{ ansible_facts.env.USER }}"
    mode: '0644'
    backup: true
