---
- name: Initialize LXC
  hosts: proxmox_lxc
  roles:
    - install_sudo
    - {role: basic_apt_package, apt_upgrade: true}
    - default_configs
    - default_cmd
    - install_docker
    - setup_exporter
    - install_tailscale
