# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/install_tailscale
- name: Add Tailscale GPG Key
  become: true
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/oracular.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: '0644'
    backup: true

- name: Add Tailscale apt repository
  become: true
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/oracular.tailscale-keyring.list
    dest: /etc/apt/sources.list.d/tailscale.list
    mode: '0644'
    backup: true

- name: Update Apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true

- name: Install Tailscale
  become: true
  ansible.builtin.apt:
    pkg:
      - tailscale
    force_apt_get: true
    install_recommends: true
    autoremove: true

- name: Tailscale Up Instruction
  ansible.builtin.debug:
    msg: "Tailscale installed successfully, Run 'tailscale up' to connect to your network"
