---
- name: Initialize Node
  hosts: proxmox_node
  roles:
    - {role: basic_apt_package, basic_apt_package_apt_upgrade: true}
    - default_configs
    - default_cmd
    - install_docker
    - setup_exporter
    - install_tailscale
